## 3. 웹 스크래핑

In [10]:
import pandas as pd
from pandas import DataFrame, Series

In [11]:
# 1) read_clipboard() : 복사 붙여넣기
#IE에서는 안되고, 크롬에서 저장하고자 하는 테이블 형태의 데이터를 복사한 후에 아래 명령어 출력하면, 데이터프레임으로 생성됨.
코스피 = pd.read_clipboard()

EmptyDataError: No columns to parse from file

In [12]:
코스피.head(10)

NameError: name '코스피' is not defined

In [13]:
# 2) read_html(): 웹 페이지 내에 있는 테이블 형태의 데이터를 모두 반환하는 함수

data = pd.read_html('https://finance.naver.com/sise/sise_market_sum.nhn', encoding = 'cp949')
df = data[1]
df = df[df.종목명.notnull()] # 종목명이 NaN인 경우에는 제거
df

,N,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE,토론실
1,1.0,삼성전자,83300.0,1000.0,+1.22%,100.0,4972829.0,5969783.0,54.70,6255903.0,21.69,9.99,NaN
2,2.0,SK하이닉스,143500.0,3500.0,+2.50%,5000.0,1044683.0,728002.0,50.04,1931739.0,21.97,9.53,NaN
3,3.0,NAVER,399500.0,16000.0,+4.17%,100.0,656232.0,164263.0,57.26,506151.0,65.52,15.22,NaN
4,4.0,LG화학,870000.0,13000.0,+1.52%,5000.0,614153.0,70592.0,44.86,223041.0,132.84,2.93,NaN
5,5.0,삼성전자우,74100.0,600.0,+0.82%,100.0,609759.0,822887.0,78.33,380340.0,19.29,NaN,NaN
9,6.0,현대차,236000.0,4000.0,+1.72%,5000.0,504257.0,213668.0,30.74,474739.0,45.89,2.04,NaN
10,7.0,삼성바이오로직스,732000.0,13000.0,+1.81%,2500.0,484328.0,66165.0,10.26,18259.0,200.99,NaN,NaN
11,8.0,삼성SDI,664000.0,25000.0,+3.91%,5000.0,456596.0,68765.0,43.08,281885.0,81.31,4.54,NaN
12,9.0,카카오,496000.0,11000.0,+2.27%,500.0,439975.0,88705.0,33.21,210056.0,-550.50,-5.81,NaN
13,10.0,셀트리온,297000.0,3500.0,+1.19%,1000.0,401032.0,135028.0,20.93,128180.0,80.27,11.19,NaN
17,11.0,기아차,86800.0,2200.0,+2.60%,5000.0,351855.0,405363.0,34.12,2218591.0,23.65,5.05,NaN
18,12.0,현대모비스,302500.0,6500.0,+2.20%,5000.0,286749.0,94793.0,40.03,171455.0,18.81,4.66,NaN
19,13.0,POSCO,298500.0,3500.0,+1.19%,5000.0,260253.0,87187.0,53.50,124733.0,16.24,3.61,NaN
20,14.0,LG전자,158500.0,500.0,+0.32%,5000.0,259382.0,163648.0,31.19,480994.0,14.56,13.23,NaN
21,15.0,LG생활건강,1570000.0,10000.0,+0.64%,5000.0,245206.0,15618.0,45.64,5577.0,34.87,17.92,NaN
25,16.0,삼성물산,123000.0,1000.0,+0.82%,100.0,229871.0,186887.0,14.87,110851.0,22.49,3.81,NaN
26,17.0,SK텔레콤,259500.0,2000.0,+0.78%,500.0,209535.0,80746.0,37.02,60359.0,13.93,6.44,NaN
27,18.0,엔씨소프트,950000.0,10000.0,+1.06%,500.0,208563.0,21954.0,50.41,19636.0,35.51,20.83,NaN
28,19.0,KB금융,49400.0,1300.0,-2.56%,5000.0,205409.0,415808.0,68.36,951616.0,5.95,8.53,NaN
29,20.0,SK이노베이션,218000.0,2000.0,+0.93%,5000.0,201575.0,92466.0,22.83,368523.0,-9.40,-13.58,NaN
33,21.0,신한지주,34800.0,700.0,-1.97%,5000.0,179777.0,516600.0,59.58,822324.0,5.16,8.20,NaN
34,22.0,SK,249000.0,4000.0,+1.63%,200.0,175197.0,70360.0,21.39,136004.0,93.26,1.11,NaN
35,23.0,삼성생명,78700.0,800.0,-1.01%,500.0,157400.0,200000.0,12.83,106264.0,15.81,3.26,NaN
36,24.0,한국전력,24350.0,250.0,-1.02%,5000.0,156318.0,641964.0,16.81,1261134.0,7.85,2.91,NaN
37,25.0,LG,89900.0,800.0,+0.90%,5000.0,155129.0,172557.0,34.98,96703.0,10.79,7.50,NaN
41,26.0,삼성전기,197500.0,3500.0,+1.80%,5000.0,147520.0,74694.0,34.87,166528.0,25.38,10.92,NaN
42,27.0,삼성에스디에스,190500.0,1500.0,+0.79%,500.0,147405.0,77378.0,12.23,26609.0,33.24,6.71,NaN
43,28.0,아모레퍼시픽,236500.0,1500.0,-0.63%,500.0,138254.0,58458.0,32.60,45814.0,464.64,0.78,NaN
44,29.0,SK바이오사이언스,169000.0,39000.0,+30.00%,500.0,129285.0,76500.0,4.66,666817.0,386.73,6.50,NaN
45,30.0,하나금융지주,40950.0,450.0,-1.09%,5000.0,122949.0,300242.0,68.54,537497.0,5.01,8.77,NaN
49,31.0,포스코케미칼,149000.0,2000.0,+1.36%,500.0,115420.0,77463.0,7.04,127494.0,323.21,2.96,NaN
50,32.0,KT&G,83600.0,3500.0,+4.37%,5000.0,114777.0,137292.0,39.67,1248329.0,9.79,13.22,NaN
51,33.0,넷마블,125000.0,1500.0,+1.21%,100.0,107358.0,85886.0,23.65,41511.0,50.63,3.54,NaN
52,34.0,롯데케미칼,303500.0,1500.0,+0.50%,5000.0,104026.0,34275.0,26.27,60516.0,65.65,1.22,NaN
53,35.0,한온시스템,17950.0,500.0,+2.87%,100.0,95817.0,533800.0,19.57,721319.0,68.25,14.98,NaN
57,36.0,S-Oil,81800.0,0.0,0.00%,2500.0,92093.0,112583.0,76.12,127718.0,-11.98,-13.07,NaN
58,37.0,삼성화재,186000.0,2000.0,-1.06%,500.0,88117.0,47375.0,45.96,39173.0,13.60,4.85,NaN
59,38.0,한화솔루션,45250.0,150.0,+0.33%,5000.0,86554.0,191278.0,17.04,514435.0,-83.64,-4.02,NaN
60,39.0,SK바이오팜,110500.0,1000.0,-0.90%,500.0,86536.0,78313.0,9.53,373925.0,-32.10,-135.18,NaN
61,40.0,한국조선해양,119500.0,1000.0,+0.84%,5000.0,84574.0,70773.0,17.04,58460.0,395.70,1.40,NaN
65,41.0,빅히트,231500.0,500.0,+0.22%,500.0,82469.0,35624.0,7.83,105378.0,NaN,56.47,NaN
66,42.0,LG디스플레이,22350.0,200.0,+0.90%,5000.0,79972.0,357816.0,24.00,612580.0,-89.40,-0.79,NaN
67,43.0,HMM,23400.0,1000.0,+4.46%,5000.0,77398.0,330763.0,11.11,3580057.0,60.94,8.93,NaN
68,44.0,고려아연,409500.0,2500.0,-0.61%,5000.0,77273.0,18870.0,22.46,11121.0,13.49,8.37,NaN
69,45.0,현대글로비스,195500.0,3500.0,+1.82%,500.0,73312.0,37500.0,33.17,48994.0,12.09,12.45,NaN
73,46.0,우리금융지주,9950.0,50.0,-0.50%,5000.0,71866.0,722268.0,25.52,688689.0,5.34,NaN,NaN
74,47.0,KT,26950.0,50.0,+0.19%,5000.0,70370.0,261112.0,42.55,292555.0,10.69,4.76,NaN
75,48.0,금호석유,219500.0,500.0,-0.23%,5000.0,66877.0,30468.0,27.42,122285.0,18.78,11.84,NaN
76,49.0,기업은행,9030.0,80.0,-0.88%,5000.0,66701.0,738664.0,11.44,974359.0,4.61,7.36,NaN
77,50.0,CJ제일제당,423500.0,2000.0,+0.47%,5000.0,63754.0,15054.0,24.80,16536.0,8.79,3.16,NaN

In [14]:
df = df[df.종목명.notnull()] # 종목명이 NaN인 경우에는 제거
df

,N,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE,토론실
1,1.0,삼성전자,83300.0,1000.0,+1.22%,100.0,4972829.0,5969783.0,54.70,6255903.0,21.69,9.99,NaN
2,2.0,SK하이닉스,143500.0,3500.0,+2.50%,5000.0,1044683.0,728002.0,50.04,1931739.0,21.97,9.53,NaN
3,3.0,NAVER,399500.0,16000.0,+4.17%,100.0,656232.0,164263.0,57.26,506151.0,65.52,15.22,NaN
4,4.0,LG화학,870000.0,13000.0,+1.52%,5000.0,614153.0,70592.0,44.86,223041.0,132.84,2.93,NaN
5,5.0,삼성전자우,74100.0,600.0,+0.82%,100.0,609759.0,822887.0,78.33,380340.0,19.29,NaN,NaN
9,6.0,현대차,236000.0,4000.0,+1.72%,5000.0,504257.0,213668.0,30.74,474739.0,45.89,2.04,NaN
10,7.0,삼성바이오로직스,732000.0,13000.0,+1.81%,2500.0,484328.0,66165.0,10.26,18259.0,200.99,NaN,NaN
11,8.0,삼성SDI,664000.0,25000.0,+3.91%,5000.0,456596.0,68765.0,43.08,281885.0,81.31,4.54,NaN
12,9.0,카카오,496000.0,11000.0,+2.27%,500.0,439975.0,88705.0,33.21,210056.0,-550.50,-5.81,NaN
13,10.0,셀트리온,297000.0,3500.0,+1.19%,1000.0,401032.0,135028.0,20.93,128180.0,80.27,11.19,NaN
17,11.0,기아차,86800.0,2200.0,+2.60%,5000.0,351855.0,405363.0,34.12,2218591.0,23.65,5.05,NaN
18,12.0,현대모비스,302500.0,6500.0,+2.20%,5000.0,286749.0,94793.0,40.03,171455.0,18.81,4.66,NaN
19,13.0,POSCO,298500.0,3500.0,+1.19%,5000.0,260253.0,87187.0,53.50,124733.0,16.24,3.61,NaN
20,14.0,LG전자,158500.0,500.0,+0.32%,5000.0,259382.0,163648.0,31.19,480994.0,14.56,13.23,NaN
21,15.0,LG생활건강,1570000.0,10000.0,+0.64%,5000.0,245206.0,15618.0,45.64,5577.0,34.87,17.92,NaN
25,16.0,삼성물산,123000.0,1000.0,+0.82%,100.0,229871.0,186887.0,14.87,110851.0,22.49,3.81,NaN
26,17.0,SK텔레콤,259500.0,2000.0,+0.78%,500.0,209535.0,80746.0,37.02,60359.0,13.93,6.44,NaN
27,18.0,엔씨소프트,950000.0,10000.0,+1.06%,500.0,208563.0,21954.0,50.41,19636.0,35.51,20.83,NaN
28,19.0,KB금융,49400.0,1300.0,-2.56%,5000.0,205409.0,415808.0,68.36,951616.0,5.95,8.53,NaN
29,20.0,SK이노베이션,218000.0,2000.0,+0.93%,5000.0,201575.0,92466.0,22.83,368523.0,-9.40,-13.58,NaN
33,21.0,신한지주,34800.0,700.0,-1.97%,5000.0,179777.0,516600.0,59.58,822324.0,5.16,8.20,NaN
34,22.0,SK,249000.0,4000.0,+1.63%,200.0,175197.0,70360.0,21.39,136004.0,93.26,1.11,NaN
35,23.0,삼성생명,78700.0,800.0,-1.01%,500.0,157400.0,200000.0,12.83,106264.0,15.81,3.26,NaN
36,24.0,한국전력,24350.0,250.0,-1.02%,5000.0,156318.0,641964.0,16.81,1261134.0,7.85,2.91,NaN
37,25.0,LG,89900.0,800.0,+0.90%,5000.0,155129.0,172557.0,34.98,96703.0,10.79,7.50,NaN
41,26.0,삼성전기,197500.0,3500.0,+1.80%,5000.0,147520.0,74694.0,34.87,166528.0,25.38,10.92,NaN
42,27.0,삼성에스디에스,190500.0,1500.0,+0.79%,500.0,147405.0,77378.0,12.23,26609.0,33.24,6.71,NaN
43,28.0,아모레퍼시픽,236500.0,1500.0,-0.63%,500.0,138254.0,58458.0,32.60,45814.0,464.64,0.78,NaN
44,29.0,SK바이오사이언스,169000.0,39000.0,+30.00%,500.0,129285.0,76500.0,4.66,666817.0,386.73,6.50,NaN
45,30.0,하나금융지주,40950.0,450.0,-1.09%,5000.0,122949.0,300242.0,68.54,537497.0,5.01,8.77,NaN
49,31.0,포스코케미칼,149000.0,2000.0,+1.36%,500.0,115420.0,77463.0,7.04,127494.0,323.21,2.96,NaN
50,32.0,KT&G,83600.0,3500.0,+4.37%,5000.0,114777.0,137292.0,39.67,1248329.0,9.79,13.22,NaN
51,33.0,넷마블,125000.0,1500.0,+1.21%,100.0,107358.0,85886.0,23.65,41511.0,50.63,3.54,NaN
52,34.0,롯데케미칼,303500.0,1500.0,+0.50%,5000.0,104026.0,34275.0,26.27,60516.0,65.65,1.22,NaN
53,35.0,한온시스템,17950.0,500.0,+2.87%,100.0,95817.0,533800.0,19.57,721319.0,68.25,14.98,NaN
57,36.0,S-Oil,81800.0,0.0,0.00%,2500.0,92093.0,112583.0,76.12,127718.0,-11.98,-13.07,NaN
58,37.0,삼성화재,186000.0,2000.0,-1.06%,500.0,88117.0,47375.0,45.96,39173.0,13.60,4.85,NaN
59,38.0,한화솔루션,45250.0,150.0,+0.33%,5000.0,86554.0,191278.0,17.04,514435.0,-83.64,-4.02,NaN
60,39.0,SK바이오팜,110500.0,1000.0,-0.90%,500.0,86536.0,78313.0,9.53,373925.0,-32.10,-135.18,NaN
61,40.0,한국조선해양,119500.0,1000.0,+0.84%,5000.0,84574.0,70773.0,17.04,58460.0,395.70,1.40,NaN
65,41.0,빅히트,231500.0,500.0,+0.22%,500.0,82469.0,35624.0,7.83,105378.0,NaN,56.47,NaN
66,42.0,LG디스플레이,22350.0,200.0,+0.90%,5000.0,79972.0,357816.0,24.00,612580.0,-89.40,-0.79,NaN
67,43.0,HMM,23400.0,1000.0,+4.46%,5000.0,77398.0,330763.0,11.11,3580057.0,60.94,8.93,NaN
68,44.0,고려아연,409500.0,2500.0,-0.61%,5000.0,77273.0,18870.0,22.46,11121.0,13.49,8.37,NaN
69,45.0,현대글로비스,195500.0,3500.0,+1.82%,500.0,73312.0,37500.0,33.17,48994.0,12.09,12.45,NaN
73,46.0,우리금융지주,9950.0,50.0,-0.50%,5000.0,71866.0,722268.0,25.52,688689.0,5.34,NaN,NaN
74,47.0,KT,26950.0,50.0,+0.19%,5000.0,70370.0,261112.0,42.55,292555.0,10.69,4.76,NaN
75,48.0,금호석유,219500.0,500.0,-0.23%,5000.0,66877.0,30468.0,27.42,122285.0,18.78,11.84,NaN
76,49.0,기업은행,9030.0,80.0,-0.88%,5000.0,66701.0,738664.0,11.44,974359.0,4.61,7.36,NaN
77,50.0,CJ제일제당,423500.0,2000.0,+0.47%,5000.0,63754.0,15054.0,24.80,16536.0,8.79,3.16,NaN

In [15]:
# 실습. 10페이지 데이터 읽어서, 코스피 기업 500개 데이터 읽어오기

코스피500 = []
url = 'https://finance.naver.com/sise/sise_market_sum.nhn?&page='

for num in range(1, 11):
    full_url = url + str(num)
    #print(full_url)
    dfs = pd.read_html(full_url, encoding = 'CP949')
    df = dfs[1]
    df = df[df.종목명.notnull()]
    코스피500.append(df)

In [16]:
코스피500[9]

,N,종목명,현재가,전일비,등락률,액면가,시가총액,상장주식수,외국인비율,거래량,PER,ROE,토론실
1,451.0,코리아써키트,13050.0,100.0,+0.77%,500.0,3082.0,23621.0,2.56,44964.0,27.59,0.21,NaN
2,452.0,동양,1290.0,5.0,+0.39%,500.0,3079.0,238684.0,8.08,131309.0,51.60,-0.05,NaN
3,453.0,아이마켓코리아,9170.0,300.0,+3.38%,500.0,3065.0,33429.0,13.29,131248.0,20.56,4.31,NaN
4,454.0,경농,14100.0,150.0,-1.05%,500.0,3059.0,21692.0,0.36,71143.0,29.19,2.47,NaN
5,455.0,대신증권우,11750.0,100.0,+0.86%,5000.0,3055.0,26000.0,11.48,42019.0,10.83,NaN,NaN
9,456.0,자화전자,17000.0,400.0,+2.41%,500.0,3043.0,17900.0,9.51,157736.0,-28.24,-0.10,NaN
10,457.0,신도리코,30100.0,0.0,0.00%,5000.0,3034.0,10080.0,21.36,4475.0,-22.61,-1.56,NaN
11,458.0,그린케미칼,12600.0,50.0,+0.40%,500.0,3024.0,24000.0,0.65,116876.0,29.23,9.33,NaN
12,459.0,제일파마홀딩스,18800.0,50.0,+0.27%,500.0,3003.0,15973.0,9.54,7231.0,26.26,2.86,NaN
13,460.0,TIGER 차이나CSI300,11730.0,50.0,+0.43%,0.0,3003.0,25600.0,1.11,117459.0,NaN,NaN,NaN
17,461.0,SNT홀딩스,18350.0,200.0,-1.08%,500.0,2992.0,16304.0,11.13,11660.0,8.00,4.62,NaN
18,462.0,서연,12700.0,1400.0,+12.39%,500.0,2982.0,23480.0,1.15,5542923.0,-5.80,-13.31,NaN
19,463.0,KPX케미칼,61100.0,1000.0,-1.61%,5000.0,2957.0,4840.0,30.59,6813.0,5.46,9.04,NaN
20,464.0,신세계푸드,76000.0,600.0,-0.78%,5000.0,2943.0,3872.0,3.85,5758.0,-13.39,-7.35,NaN
21,465.0,동부건설,12850.0,0.0,0.00%,5000.0,2918.0,22706.0,2.13,15269.0,6.51,10.10,NaN
25,466.0,KODEX 선진국MSCI World,17955.0,5.0,-0.03%,0.0,2909.0,16200.0,0.00,8528.0,NaN,NaN,NaN
26,467.0,아모레G3우(전환),40950.0,50.0,-0.12%,500.0,2904.0,7092.0,6.83,3043.0,379.17,NaN,NaN
27,468.0,휴비스,8390.0,70.0,+0.84%,5000.0,2895.0,34500.0,5.40,101636.0,3.52,19.01,NaN
28,469.0,E1,42050.0,350.0,+0.84%,5000.0,2885.0,6860.0,4.04,7890.0,4.20,-3.63,NaN
29,470.0,신대양제지,71500.0,500.0,+0.70%,5000.0,2881.0,4030.0,8.94,5077.0,6.02,14.26,NaN
33,471.0,팜스코,7840.0,80.0,+1.03%,500.0,2879.0,36728.0,4.78,121792.0,23.20,4.21,NaN
34,472.0,금호에이치티,2275.0,40.0,+1.79%,500.0,2850.0,125258.0,2.23,896801.0,-24.46,-0.05,NaN
35,473.0,경인양행,6880.0,0.0,0.00%,500.0,2842.0,41306.0,2.50,45404.0,275.20,6.57,NaN
36,474.0,KISCO홀딩스,15350.0,0.0,0.00%,1000.0,2836.0,18476.0,8.84,5240.0,5.58,5.58,NaN
37,475.0,동방,7010.0,110.0,+1.59%,1000.0,2802.0,39972.0,1.62,4394435.0,-53.51,-8.33,NaN
41,476.0,현대비앤지스틸,18550.0,0.0,0.00%,5000.0,2797.0,15079.0,4.48,54305.0,11.94,5.68,NaN
42,477.0,코오롱,22050.0,100.0,+0.46%,5000.0,2784.0,12626.0,11.93,18209.0,3.00,-2.61,NaN
43,478.0,HANARO MSCI Korea TR,17160.0,265.0,+1.57%,0.0,2780.0,16200.0,0.00,408.0,NaN,NaN,NaN
44,479.0,계룡건설,31050.0,350.0,+1.14%,5000.0,2773.0,8931.0,20.16,49221.0,2.95,18.69,NaN
45,480.0,SBS미디어홀딩스,1975.0,20.0,+1.02%,500.0,2763.0,139896.0,1.93,27169.0,-1.86,-16.34,NaN
49,481.0,도화엔지니어링,8190.0,80.0,+0.99%,500.0,2762.0,33720.0,1.66,26973.0,15.48,7.00,NaN
50,482.0,대영포장,2530.0,105.0,+4.33%,500.0,2742.0,108395.0,1.29,10722476.0,58.84,7.42,NaN
51,483.0,아시아나IDT,24550.0,50.0,-0.20%,500.0,2725.0,11100.0,0.25,47463.0,-193.31,-5.44,NaN
52,484.0,삼영무역,14750.0,0.0,0.00%,500.0,2724.0,18467.0,19.75,4468.0,8.43,10.32,NaN
53,485.0,KTB투자증권,4500.0,25.0,+0.56%,5000.0,2714.0,60314.0,22.73,260508.0,5.00,9.18,NaN
57,486.0,KEC,2325.0,20.0,+0.87%,500.0,2713.0,116707.0,3.40,646141.0,-11.57,-8.99,NaN
58,487.0,센트랄모텍,31300.0,300.0,+0.97%,500.0,2695.0,8610.0,0.38,58847.0,40.03,5.74,NaN
59,488.0,한농화성,17200.0,650.0,+3.93%,500.0,2690.0,15637.0,0.12,561954.0,21.83,8.58,NaN
60,489.0,삼익THK,12800.0,0.0,0.00%,500.0,2688.0,21000.0,34.58,9226.0,60.38,2.36,NaN
61,490.0,TIGER 글로벌4차산업혁신기술(합성 H),17820.0,140.0,+0.79%,0.0,2673.0,15000.0,0.03,24753.0,NaN,NaN,NaN
65,491.0,사조산업,52900.0,2800.0,+5.59%,5000.0,2645.0,5000.0,3.19,109746.0,-27.52,-3.13,NaN
66,492.0,SNT중공업,7930.0,80.0,+1.02%,2500.0,2637.0,33253.0,9.80,16764.0,31.59,1.37,NaN
67,493.0,금호석유우,85900.0,700.0,-0.81%,5000.0,2597.0,3023.0,13.32,8827.0,7.35,NaN,NaN
68,494.0,광주신세계,162000.0,1500.0,-0.92%,5000.0,2592.0,1600.0,12.21,967.0,6.01,6.35,NaN
69,495.0,현대약품,8080.0,160.0,-1.94%,500.0,2586.0,32000.0,1.89,432536.0,118.82,2.52,NaN
73,496.0,대원강업,4155.0,65.0,+1.59%,500.0,2576.0,62000.0,2.07,126569.0,-39.95,-1.36,NaN
74,497.0,제주은행,7970.0,30.0,-0.37%,5000.0,2561.0,32129.0,2.02,308455.0,14.62,3.48,NaN
75,498.0,세방,13250.0,150.0,+1.15%,500.0,2558.0,19309.0,4.32,30892.0,127.40,0.68,NaN
76,499.0,흥국화재,3980.0,20.0,-0.50%,5000.0,2557.0,64243.0,2.49,69462.0,17.23,5.51,NaN
77,500.0,CJ제일제당 우,190500.0,500.0,+0.26%,5000.0,2529.0,1327.0,27.85,1271.0,3.96,NaN,NaN

In [17]:
data = pd.concat(코스피500, axis = 0) # --> 다음 차시에 더 자세히 배움

In [18]:
# 결과 데이터를 html 파일로 내보내기
data.to_html('data/코스피500.html', encoding = 'CP949')

In [19]:
# read_html()이 잘 안되거나, 테이블 형태가 아닌 전문적으로 다른 형태의 데이터를 읽어오려고 할 때
# 3) Selenium으로 간단한 스크래핑 해보기 
# 삼성전자의 일별 시세 알아보기 (https://finance.naver.com/item/sise.nhn?code=005930)
삼성전자url = 'https://finance.naver.com/sise/sise_market_sum.nhn?&page=1'
삼성주식 = pd.read_html(삼성전자url, encoding = 'cp949')

# 값이 나오네!

In [20]:
len(삼성주식)
삼성주식[2]

# 하지만 내가 원하는 답은 없지..
#iframe = inline frame => 웹 페이지 안에 또 다른 웹페이지

   0   1   2   3   4   5   6   7   8   9   10  11
0   1   2   3   4   5   6   7   8   9  10  다음  맨뒤

In [21]:
# iframe에 있는 내가 원하는 url로 변경해서 다시 시도
삼성전자url = 'https://finance.naver.com/item/sise_day.nhn?code=005930&page=1'
삼성주식 = pd.read_html(삼성전자url, encoding = 'cp949')

# No tables Found라는 에러 발생
# 웹사이트가 데이터를 로딩하는 시간이 존재하나, pandas의 read_html() 함수는 이 시간을 기다려주지 않는다. 
# 즉, 웹페이지에 데이터가 표시되기도 전에 html 문서를 읽기 때문에 데이터를 읽을 수가 없는 것이다. 
# 이러한 문제는 Selenium 과 같은 외부 라이브러리를 활용하여 해결할 수 있습니다.

ValueError: No tables found

In [32]:
# 1. selenium 설치
# conda install selenium

from selenium import webdriver

In [33]:
# 2. chromedriver 다운로드하여 적절한 위치에 옮기기
# 다운로드 사이트: https://sites.google.com/a/chromium.org/chromedriver/downloads
# 자신의 크롬 브라우저의 버전에 맞는 파일을 다운로드

In [34]:
driver = webdriver.Chrome('chromedriver')
driver.implicitly_wait(3)

SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 87
Current browser version is 89.0.4389.82 with binary path C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

In [ ]:
driver.get(삼성전자url) # selenium이 해당 웹페이지를 실행
삼성_일별 = driver.page_source

In [ ]:
삼성_일별

In [ ]:
삼성주식 = pd.read_html(삼성_일별, encoding = 'cp949')

In [ ]:
len(삼성주식)

In [ ]:
삼성주식 = 삼성주식[0][삼성주식[0].날짜.notnull()]

In [ ]:
삼성주식

In [ ]:
# 실습. 모든 기간의 삼성전자 주식 데이터를 스크래핑하여 삼성전자_일별주가.xlsx로 저장
삼성전자url = 'https://finance.naver.com/item/sise_day.nhn?code=005930&page='
일별주가 = []
for i in range(1, 619):
    full_url = 삼성전자url + str(i)
    driver.get(full_url) 
    삼성_일별 = driver.page_source
    삼성주식 = pd.read_html(삼성_일별, encoding = 'cp949')
    삼성주식 = 삼성주식[0][삼성주식[0].날짜.notnull()]
    일별주가.append(삼성주식)
    
삼성전자_일별주가 = pd.concat(일별주가, axis = 0)

In [ ]:
삼성전자_일별주가.to_excel('삼성전자_일별주가.xlsx')

## 4. 데이터베이스에서 읽기
### 파이썬에서 sqlite를 내장하고 있음

In [ ]:
import sqlite3

In [ ]:
#테이블 생성 SQL 정의
테이블생성 = 'CREATE TABLE locations \
                (a varchar[20], b varchar[20], c integer)'

In [ ]:
#sqlite 접속
conn = sqlite3.connect('temp.db')

In [ ]:
#테이블 생성 SQL 수행 
conn.execute(테이블생성)

In [ ]:
#conn.execute('drop table locations')

In [ ]:
# commit() 수행. - SQL 수행 후, commit을 해야만, 데이터베이스에 SQL 구문이 적용됨 
conn.commit()

In [35]:
#생성된 테이블에 저장할 데이터 정의
data = [['서울','강남', 15]
       ,['서울','강동', 10]
       ,['서울','동대문', 7]
       ,['서울','양천', 12]
       ,['성남','분당', 12]
       ,['수원','영통', 15]
       ,['성남','중원', 11]
       ,['수원','팔달', 14]
       ]

In [36]:
# 데이터 적재 SQL 정의 
적재 = 'insert into locations values (?,?,?)'

In [37]:
#데이터 적재 SQL 수행
conn.executemany(적재, data)

NameError: name 'conn' is not defined

In [23]:
# commit() 수행
conn.commit()

NameError: name 'conn' is not defined

In [24]:
#Select SQL 실행1
pd.read_sql('SELECT * FROM locations', conn)

NameError: name 'conn' is not defined

In [25]:
#Select SQL 실행2
pd.read_sql('SELECT sum(c) FROM locations \
            GROUP BY a', conn)

NameError: name 'conn' is not defined

In [26]:
# 데이터베이스의 테이블 크기가 큰 경우에는 cursor 사용하기
cursor = conn.execute('SELECT * FROM locations')

NameError: name 'conn' is not defined

In [27]:
rows = cursor.fetchmany(2)
rows

NameError: name 'cursor' is not defined

In [28]:
DataFrame(rows)

NameError: name 'rows' is not defined

In [29]:
cursor.fetchmany(10)

NameError: name 'cursor' is not defined

In [30]:
cursor.close()

NameError: name 'cursor' is not defined

In [31]:
conn.close()

NameError: name 'conn' is not defined